### ISSUE TITLE
Not working on iOS/iPadOS?

### ISSUE THREAD

**Issue by wkjarosz** [Armchair-Software/emscripten-browser-file#3]
Thank you for the great library. I incorporated the `upload` functionality into my web app, and it works great in browser on a laptop (macOS), but it seemingly doesn't work on iOS/iPadOS. On my iPhone/iPad the `upload` function doesn't bring up any file selection dialog, and the handler callback is never called.

Is this a known issue, or am I perhaps not using the library properly?

I don't know enough about emscripten to debug/fix this myself, but with guidance am happy to provide more details.

Thanks again.

**Comment by slowriot** [comment]
Please re-open this issue if it isn't resolved by @AnatoliyProjects' fix above.
